#!/bin/bash
echo hello techiehorizon
echo
echo welcome to the world
echo
echo hi everyone
echo
echo this is saleem pasha
echo
echo worked as a devops engineer for techiehorizon company for last 5 years
echo
echo currently i have been working for xxx client, where our company is managing two applications
